LABEL_NAMES = {
    0: 'background',
    1: 'affiliation',
    2: 'comment',
    3: 'date',
    4: 'diagram',
    5: 'enumeration',
    6: 'footnote',
    7: 'plot',
    8: 'heading',
    9: 'image_caption',
    10: 'legend',
    11: 'logo',
    12: 'map',
    13: 'screenshot',
    14: 'text',
    15: 'presentation_title',
    16: 'code',
    17: 'realistic_img',
    18: 'slide_num',
    19: 'drawing',
    20: 'table',
    21: 'slide_title',
    22: 'website',
    23: 'hand_math',
    24: 'typed_math'
}